### ISSUE TITLE
Simple Client Examples Crashes When Server is Present

### ISSUE THREAD

**Issue by jthomerson** [Syphon/Java#6]
I followed the steps in the README and everything seemed to build correctly. The `jsyphon.test.ServerTest` example runs fine. But, the `jsyphon.test.ClientTest` fails every time there's actually a Syphon stream present. I can start `ClientTest` if there's no server running / no stream present, and it runs fine. But the moment that I start a server, the client crashes. If the server is running at the time the client test is started, the client window never opens - the crash happens immediately. I have tried this with three servers: the Java ServerTest example (in the same codebase), the Simple Server from the Syphon/Simple project (downloaded one, and one running in XCode), and Chroma Key Live by Zach Poff.

Here's some information from the startup and subsequent crash:

```
objc[23069]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/bin/java (0x10b98b4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10da094e0). One of the two will be used. Which one is undefined.
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethod
WARNING: JNI local refs: 384, exceeds capacity: 34
WARNING: JNI local refs: 383, exceeds capacity: 33
WARNING: JNI local refs: 392, exceeds capacity: 42
WARNING: JNI local refs: 394, exceeds capacity: 44
WARNING: JNI local refs: 34, exceeds capacity: 32
   at org.eclipse.jdt.launching.internal.weaving.ClassfileTransformer.transform(ClassfileTransformer.java:28)
   at org.eclipse.jdt.launching.internal.javaagent.Premain$1.transform(Premain.java:73)
   at sun.instrument.TransformerManager.transform(TransformerManager.java:188)
   at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428)
   at java.lang.ClassLoader.defineClass1(Native Method)
   at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
   at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
   at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
   at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
   at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
   at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
   at java.security.AccessController.doPrivileged(Native Method)
   at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
   - locked <0x000000076aff2e70> (a java.lang.Object)
   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
   at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:495)
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallObjectMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethod
   at java.lang.ClassLoader$NativeLibrary.load(Native Method)
   at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
   - locked <0x000000076ab06818> (a java.util.Vector)
   - locked <0x000000076ab06870> (a java.util.Vector)
   at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
   at java.lang.Runtime.load0(Runtime.java:809)
   - locked <0x000000076ab1b328> (a java.lang.Runtime)
   at java.lang.System.load(System.java:1086)
   at java.lang.ClassLoader$NativeLibrary.load(Native Method)
   at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
   - locked <0x000000076ab06818> (a java.util.Vector)
   - locked <0x000000076ab06870> (a java.util.Vector)
   at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1845)
   at java.lang.Runtime.loadLibrary0(Runtime.java:870)
   - locked <0x000000076ab1b328> (a java.lang.Runtime)
   at java.lang.System.loadLibrary(System.java:1122)
   at java.awt.Toolkit$3.run(Toolkit.java:1636)
   at java.awt.Toolkit$3.run(Toolkit.java:1634)
   at java.security.AccessController.doPrivileged(Native Method)
   at java.awt.Toolkit.loadLibraries(Toolkit.java:1633)
   at java.awt.Toolkit.<clinit>(Toolkit.java:1668)
   at org.lwjgl.MacOSXSysImplementation.<clinit>(MacOSXSysImplementation.java:51)
   at org.lwjgl.Sys.createImplementation(Sys.java:135)
   at org.lwjgl.Sys.<clinit>(Sys.java:116)
   at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
   at jsyphon.test.ClientTest.start(ClientTest.java:40)
   at jsyphon.test.ClientTest.main(ClientTest.java:113)
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethod
   at sun.lwawt.macosx.LWCToolkit.initIDs(Native Method)
   at sun.lwawt.macosx.LWCToolkit.<clinit>(LWCToolkit.java:102)
   at java.lang.Class.forName0(Native Method)
   at java.lang.Class.forName(Class.java:264)
   at java.awt.Toolkit$2.run(Toolkit.java:860)
   at java.awt.Toolkit$2.run(Toolkit.java:855)
   at java.security.AccessController.doPrivileged(Native Method)
   at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
   - locked <0x000000076b3e5380> (a java.lang.Class for java.awt.Toolkit)
   at org.lwjgl.MacOSXSysImplementation.<clinit>(MacOSXSysImplementation.java:51)
   at org.lwjgl.Sys.createImplementation(Sys.java:135)
   at org.lwjgl.Sys.<clinit>(Sys.java:116)
   at org.lwjgl.opengl.Display.<clinit>(Display.java:135)
   at jsyphon.test.ClientTest.start(ClientTest.java:40)
   at jsyphon.test.ClientTest.main(ClientTest.java:113)
WARNING in native method: JNI call made without checking exceptions when required to from CallObjectMethod
   at java.lang.ClassLoader.findBootstrapClass(Native Method)
   at java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1015)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:413)
   - locked <0x000000076b7f3910> (a java.lang.Object)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
   - locked <0x000000076b7f3880> (a java.lang.Object)
   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
   at org.lwjgl.opengl.Display.setDisplayMode(Display.java:237)
   at jsyphon.test.ClientTest.start(ClientTest.java:40)
   at jsyphon.test.ClientTest.main(ClientTest.java:113)
WARNING: JNI local refs: 33, exceeds capacity: 32
   at org.lwjgl.opengl.Display.create(Display.java:827)
   - locked <0x000000076b7f8d30> (a java.lang.Object)
   at org.lwjgl.opengl.Display.create(Display.java:757)
   - locked <0x000000076b7f8d30> (a java.lang.Object)
   at org.lwjgl.opengl.Display.create(Display.java:739)
   at jsyphon.test.ClientTest.start(ClientTest.java:41)
   at jsyphon.test.ClientTest.main(ClientTest.java:113)
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethod
   at java.lang.ClassLoader$NativeLibrary.find(Native Method)
   at java.lang.ClassLoader.findNative(ClassLoader.java:1963)
   - locked <0x000000076ab59fe8> (a java.util.Vector)
   at org.lwjgl.opengl.MacOSXPeerInfo.nChoosePixelFormat(Native Method)
   at org.lwjgl.opengl.MacOSXPeerInfo.choosePixelFormat(MacOSXPeerInfo.java:58)
   at org.lwjgl.opengl.MacOSXPeerInfo.<init>(MacOSXPeerInfo.java:53)
   at org.lwjgl.opengl.MacOSXCanvasPeerInfo.<init>(MacOSXCanvasPeerInfo.java:61)
   at org.lwjgl.opengl.MacOSXDisplayPeerInfo.<init>(MacOSXDisplayPeerInfo.java:48)
   at org.lwjgl.opengl.MacOSXDisplay.createPeerInfo(MacOSXDisplay.java:321)
   at org.lwjgl.opengl.DrawableGL.setPixelFormat(DrawableGL.java:61)
   at org.lwjgl.opengl.Display.create(Display.java:846)
   - locked <0x000000076b7f8d30> (a java.lang.Object)
   at org.lwjgl.opengl.Display.create(Display.java:757)
   - locked <0x000000076b7f8d30> (a java.lang.Object)
   at org.lwjgl.opengl.Display.create(Display.java:739)
   at jsyphon.test.ClientTest.start(ClientTest.java:41)
   at jsyphon.test.ClientTest.main(ClientTest.java:113)
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticBooleanMethod
   at java.lang.ClassLoader.findBootstrapClass(Native Method)
   at java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1015)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:413)
   - locked <0x000000076b83a508> (a java.lang.Object)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
   - locked <0x000000076b83a470> (a java.lang.Object)
   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
   at org.lwjgl.opengl.MacOSXCanvasPeerInfo.<init>(MacOSXCanvasPeerInfo.java:57)
   at org.lwjgl.opengl.MacOSXDisplayPeerInfo.<init>(MacOSXDisplayPeerInfo.java:48)
   at org.lwjgl.opengl.MacOSXDisplay.createPeerInfo(MacOSXDisplay.java:321)
   at org.lwjgl.opengl.DrawableGL.setPixelFormat(DrawableGL.java:61)
   at org.lwjgl.opengl.Display.create(Display.java:846)
   - locked <0x000000076b7f8d30> (a java.lang.Object)
   at org.lwjgl.opengl.Display.create(Display.java:757)
   - locked <0x000000076b7f8d30> (a java.lang.Object)
   at org.lwjgl.opengl.Display.create(Display.java:739)
   at jsyphon.test.ClientTest.start(ClientTest.java:41)
   at jsyphon.test.ClientTest.main(ClientTest.java:113)
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethod
   at java.lang.ClassLoader.findBootstrapClass(Native Method)
   at java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1015)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:413)
   - locked <0x000000076b8470e0> (a java.lang.Object)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
   - locked <0x000000076b847050> (a java.lang.Object)
   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
   at org.lwjgl.LWJGLUtil.isMacOSXEqualsOrBetterThan(LWJGLUtil.java:525)
   at org.lwjgl.opengl.MacOSXDisplay.createWindow(MacOSXDisplay.java:139)
   at org.lwjgl.opengl.Display.createWindow(Display.java:306)
   at org.lwjgl.opengl.Display.create(Display.java:848)
   - locked <0x000000076b7f8d30> (a java.lang.Object)
   at org.lwjgl.opengl.Display.create(Display.java:757)
   - locked <0x000000076b7f8d30> (a java.lang.Object)
   at org.lwjgl.opengl.Display.create(Display.java:739)
   at jsyphon.test.ClientTest.start(ClientTest.java:41)
   at jsyphon.test.ClientTest.main(ClientTest.java:113)
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethod
   at org.lwjgl.opengl.MacOSXDisplay.nCreateWindow(Native Method)
   at org.lwjgl.opengl.MacOSXDisplay.createWindow(MacOSXDisplay.java:158)
   at org.lwjgl.opengl.Display.createWindow(Display.java:306)
   at org.lwjgl.opengl.Display.create(Display.java:848)
   - locked <0x000000076b7f8d30> (a java.lang.Object)
   at org.lwjgl.opengl.Display.create(Display.java:757)
   - locked <0x000000076b7f8d30> (a java.lang.Object)
   at org.lwjgl.opengl.Display.create(Display.java:739)
   at jsyphon.test.ClientTest.start(ClientTest.java:41)
   at jsyphon.test.ClientTest.main(ClientTest.java:113)
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
   at java.lang.ClassLoader.findBootstrapClass(Native Method)
   at java.lang.ClassLoader.findBootstrapClassOrNull(ClassLoader.java:1015)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:413)
   - locked <0x000000076b94fd18> (a java.lang.Object)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
   - locked <0x000000076b94fc90> (a java.lang.Object)
   at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
   at org.lwjgl.opengl.MacOSXDisplay.hasWheel(MacOSXDisplay.java:362)
   at org.lwjgl.input.Mouse.create(Mouse.java:272)
   at org.lwjgl.input.Mouse.create(Mouse.java:297)
   - locked <0x000000076b7f8d30> (a java.lang.Object)
   at org.lwjgl.opengl.Display.initControls(Display.java:1066)
   at org.lwjgl.opengl.Display.createWindow(Display.java:313)
   at org.lwjgl.opengl.Display.create(Display.java:848)
   - locked <0x000000076b7f8d30> (a java.lang.Object)
   at org.lwjgl.opengl.Display.create(Display.java:757)
   - locked <0x000000076b7f8d30> (a java.lang.Object)
   at org.lwjgl.opengl.Display.create(Display.java:739)
   at jsyphon.test.ClientTest.start(ClientTest.java:41)
   at jsyphon.test.ClientTest.main(ClientTest.java:113)
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticObjectMethod
   at org.lwjgl.opengl.MacOSXContextImplementation.nCreate(Native Method)
   at org.lwjgl.opengl.MacOSXContextImplementation.create(MacOSXContextImplementation.java:49)
   at org.lwjgl.opengl.ContextGL.<init>(ContextGL.java:132)
   - locked <0x000000076ba0ef78> (a org.lwjgl.opengl.ContextGL)
   at org.lwjgl.opengl.Display.create(Display.java:850)
   - locked <0x000000076b7f8d30> (a java.lang.Object)
   at org.lwjgl.opengl.Display.create(Display.java:757)
   - locked <0x000000076b7f8d30> (a java.lang.Object)
   at org.lwjgl.opengl.Display.create(Display.java:739)
   at jsyphon.test.ClientTest.start(ClientTest.java:41)
   at jsyphon.test.ClientTest.main(ClientTest.java:113)
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
JSyphonServerList.getList() = []
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING: JNI local refs: 33, exceeds capacity: 32
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING: JNI local refs: 66, exceeds capacity: 65
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod
WARNING: JNI local refs: 1302, exceeds capacity: 34
JSyphonServerList.getList() = [{SyphonServerDescriptionDictionaryVersionKey=0, SyphonServerDescriptionIconKey=null, SyphonServerDescriptionSurfacesKey=[{SyphonSurfaceType=SyphonSurfaceTypeIOSurface}], SyphonServerDescriptionNameKey=, SyphonServerDescriptionAppNameKey=Simple Server, SyphonServerDescriptionUUIDKey=info.v002.Syphon.63833F93-1537-4063-B602-3FBF2FA271B9}]
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fff3ae3771c, pid=23069, tid=0x0000000000000307
#
# JRE version: Java(TM) SE Runtime Environment (8.0_111-b14) (build 1.8.0_111-b14)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (25.111-b14 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# C  [OpenGL+0xa71c]  GLCDescribePixelFormat+0xe
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/jrthomer/git-clones/random/syphon-java/JSyphon/hs_err_pid23069.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
# The crash happened outside the Java Virtual Machine in native code.
# See problematic frame for where to report the bug.
#
```

Note that there are two lines where the log shows `JSyphonServerList.getList() = ...`. Both of these come from this line of code inside the client test's while loop:

```java
      int lastListLen = -1;
      while (!Display.isCloseRequested()) {
         ArrayList<HashMap<String, String>> list = JSyphonServerList.getList();
         if (list.size() != lastListLen) {
            System.out.println("JSyphonServerList.getList() = " + list);
            lastListLen = list.size();
         }
```

Any ideas? Thanks!

**Comment by vade** [comment]
`WARNING in native method: JNI call made without checking exceptions when required to from CallVoidMethod"
`
Interesting - looks like the JNI interface requirements have changes since er, the 6 year gap when we wrote this. Ha.

All of my Java / JNI has been dumped a while ago - I suspect java 8 has some updates that we aren't compatible with or play nicely with?

A quick perusal of the error indicates:

https://github.com/dropbox/djinni/issues/152
https://community.oracle.com/thread/3783234

And : https://github.com/dropbox/djinni/issues/153


The crasher is apparently in

`# C  [OpenGL+0xa71c]  GLCDescribePixelFormat+0xe`

Which is an OpenGL query - however im wondering if your apparently tight loop is the issue?

It looks like JWGL is trying to create a display ? What happens if you one-line it without a loop?

**Comment by jthomerson** [comment]
Thanks for the quick feedback! Sorry I wasn't clearer about where those lines of code were - I added that logging to this location in the example from this repo: https://github.com/Syphon/Java/blob/3093475cdbe8e989eebb8629195ec30a66cf617c/JSyphon/src/jsyphon/test/ClientTest.java#L42

I also forgot to mention that I had added the `-Xcheck:jni` argument to see if it gave me more debugging info. Same crash with or without it, just much more information with it.

I also removed the `while` loop and just had the (same code I linked to above) run through what _was_ the `while` loop one time - same crash if there's a server running.

Like you, my JNI knowledge has long been purged so at this point I'm just poking in the dark. Was hoping someone saw it and had an 'Aha!' moment. If you have any other ideas, let me know.

**Comment by jthomerson** [comment]
FWIW, I also took out all of the LWJGL code and just left the polling of the JSyphon client (with sysout calls to log it) - same crash.

**Comment by bangnoise** [comment]
This will be due to an API change in SyphonClient - the README suggests you update to the latest framework without suggesting you check the consequences of that. Updates incoming this week or next...

**Comment by bangnoise** [comment]
Might be wrong on that, should read code before I type... anyway, taking a look.

**Comment by bangnoise** [comment]
The ClientTest was erroneously calling init() on the JSyphonClient before LWGL was set up. I've fixed ClientTest and fixed the library so it won't crash if you do that (instead isValid() will return false).
